### ISSUE TITLE
No code signature found.

### ISSUE THREAD

**Issue by imboii** [Lrdsnow/purepkg#11]
yeah well the title says it all. i,m installing this app from a xmlinux os in a rasberrpy pi 400. here is the log:

ideviceinstaller -i /home/imboii/Downloads/e.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/PurePKG.app/SC_Info/PurePKG.sinf in archive!
Copying '/home/imboii/Downloads/e.ipa' to device... DONE.
Installing 'uwu.lrdsnow.purepkg'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: PreflightingApplication (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe800801c: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.zHdddB/extracted/Payload/PurePKG.app : 0xe800801c (No code signature found.)

**Comment by Lrdsnow** [comment]
Its not meant to have a signature, you have to sign it yourself
