### ISSUE TITLE
integrity fail

### ISSUE THREAD

**Issue by imboii** [Lrdsnow/purepkg#12]
so i signed the app and tried to install it but i got the error:  Unable to install "PurePKG" This app cannot be installed because its integrity could not be verified.

**Comment by Lrdsnow** [comment]
still an issue with how you're signing it. please do not create another issue, just comment on this closed one if you still need help

**Comment by imboii** [comment]
how should i sign it then so i dont get that error?

**Comment by Lrdsnow** [comment]
With TrollStore or installing it via the repo (through Sileo, Zebra, Saily or Installer)

**Comment by imboii** [comment]
Installer? Where can i find that?

**Comment by Lrdsnow** [comment]
Installer is just another Jailbreak package manager just like Saily, Zebra, Sileo and PurePKG, I recommend installing PurePKG through Trollstore though also if you are not on a jailbreakable version (A9-A11: iOS 13-18 or A12+ iOS 13-16.5) I dont recommend installing PurePKG

**Comment by imboii** [comment]
I'm on iOS 16.7.8 and have been looking for a package manager and thought this one would work but if you know any that are made for my version then it would be nice if you could tell me
