### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ToneXum** [Lrdsnow/purepkg#14]
I find myself unable to launch PurePKG (version 1.7).

I am unsure how to extract logs, so please advise me if you need them.

Specs:
- iPad Pro 5th Gen
- iPadOS 16.2
- Jailbroken with Dopamine
- Installed via Sileo

Oh, and your Discord invite in the readme expired...

**Comment by Lrdsnow** [comment]
Does the TIPA work? also thx I updated the discord invite

**Comment by ToneXum** [comment]
TrollStore IPA works without further complications
