### ISSUE TITLE
Extreme Lag On A13

### ISSUE THREAD

**Issue by luhgarlicbread** [Lrdsnow/purepkg#4]
I’ve tried both the arm64 deb & the .tipa on my iPhone 11 (A13) and I am experiencing extreme lag with PurePKG. The application takes a while to respond to a single input, if it does at all.

**Comment by Lrdsnow** [comment]
Unfortunately all you can do is enable basic ui mode for now, that should make it usable, im still trying to fix performance <A15 so

**Comment by luhgarlicbread** [comment]
> Unfortunately all you can do is enable basic ui mode for now, that should make it usable, im still trying to fix performance <A15 so

idk man I can't even enable it lol, as far as I can tell, clicking it ain't done nothing. Good luck on developing bro. God bless :D

**Comment by Lrdsnow** [comment]
v1.5 fixed it lol

**Comment by luhgarlicbread** [comment]
yuhhh that's what's up
